# Generated by Django 2.1.3 on 2018-12-21 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=255)),
                ('previous_value', models.FloatField(default=-1)),
                ('current_value', models.FloatField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('counters', models.ManyToManyField(to='commapp.Counter')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartments', models.ManyToManyField(to='commapp.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commapp.UserEntity'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commapp.ServiceProviderEntity'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='service_providers',
            field=models.ManyToManyField(to='commapp.ServiceProvider'),
        ),
    ]
